name = "FuxPack"
author = "Fux Games"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8da68d2ebaf7a69a8e48ea375d5510cd4f8d6fc427e5f7834f35270502f37922"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
