name = "FuxPack"
author = "Fux Games"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ece7cd2c09ca8ea13ecbd2362490b153ab70f0edf297d1fa6e93691ad088e4f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
