name = "FuxPack"
author = "Fux Games"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "333dea961d4c1d44c74c77878c45e5d750a64c3352ff5759449b28fe0f9909fd"

[versions]
fabric = "0.14.21"
minecraft = "1.19.3"
