name = "FuxPack"
author = "Fux Games"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6250ff59a1e372765b1faab142ed013e67f1603b980d63b27ab137e14003d766"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
