name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
      - run: go install github.com/packwiz/packwiz@latest
      - run: curl -Lo /usr/local/bin/-i https://raw.githubusercontent.com/pixelcmtd/-i/daddy/-i
      - run: chmod +x /usr/local/bin/-i
      - run: just
      - run: just --evaluate | sed 's/ *:= */=/;s/"//' >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.name }}-${{ env.version }}.mrpack
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.name }}AU ${{ env.branch }}.zip
          if-no-files-found: error
